version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - env/.dev
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql_data/data/
    environment:
      MYSQL_DATABASE: econowallet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3320:3306

volumes:
  mysql_data: